### ISSUE TITLE
libftdi installation - python version

### ISSUE THREAD

**Issue by Claire06** [adafruit/Adafruit-FT232H-Breakout-PCB#1]
Hello everyone, 

I am following the instructions on https://learn.adafruit.com/adafruit-ft232h-breakout/windows-setup
to install the ftdi library on my computer and I am getting errors when importing the ftdi1. It is written to use python2.7 but as it hasn't been updated since 2014 I am trying with python3.6. Do you think that my error is because I am using python3.6 or should this version of python be supported?

Thank you very much,

Claire

**Comment by ladyada** [comment]
hiya check the new guide at https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h
