### ISSUE TITLE
Version 2 Silk screen vs Schematic +5 +3 backwards

### ISSUE THREAD

**Issue by K2AAE** [adafruit/Adafruit-FT232H-Breakout-PCB#2]
The silkscreen on version 2 PCB shows pin 1=3V pin 2=5V - which matches the eagle AdafruitFT232H.sch
The schematic at https://learn.adafruit.com/assets/88382
shows pin 1 an up arrow, what ever that means, pin 2 as 3V

**Comment by ladyada** [comment]
hi, you are not reading the schematic completely - there is no error.
